### ISSUE TITLE
Failed to query getAdopters() in test.py

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/etch-demos#1]
First deployed pet-shop contract (adoption.etch) by running: `python deploy.py pet`

But get the following error when running the following `print(contract.query(api, 'getAdopters'))` in test.py:

```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-a6f4a752138d> in <module>

RuntimeError: Failed to make requested query with no error message.```

**Comment by Kevin-Chen0** [comment]
See interact-checkpoint.ipynb for reference:

https://github.com/fetchai/etch-demos/blob/master/demos/.ipynb_checkpoints/interact-checkpoint.ipynb

**Comment by NelisDrost** [comment]
Assuming that this is the etch code in the contract: https://github.com/fetchai/etch-demos/blob/master/demos/pet-shop/adoption.etch

Then it appears that you never initialise the adopters array - you need an @init function with an array instantiation, e.g.:
`use adopters;
adopters.set(Array<Address>());`

Though looking at how its used, you probably want to use a persistent sharded global, see https://docs.fetch.ai/etch-language/persistent-globals/

**Comment by Kevin-Chen0** [comment]
Thanks will try, does it matter how I name the @init function? Will the api automatically execute the @init function (if available) upon deployment? `api.sync(api.contracts.create(owner, contract, 10000))
`

**Comment by NelisDrost** [comment]
The name shouldn't matter, and it will be called on creation.

**Comment by Kevin-Chen0** [comment]
Here is my new contract now:

```
persistent adopters : Array<Address>;


@init
function constructor()

    use adopters;
    adopters.set(Array<Address>());

endfunction


@action
function adopt(petId: Int32) : Int32

    use adopters;
    var adopt_arr = adopters.get();

    // assert(petId >= 0 && petId <= 15);
    assert(petId >= 0);
    assert(petId <= 15);

    var sender_addr = getContext().transaction().from();
    adopt_arr[petId] = sender_addr;
    adopters.set(adopt_arr);

    return petId;

endfunction


@query
function getAdopters() : Array<Address>

    use adopters;
    return adopters.get();

endfunction

```
However, I'm still getting the following error: 

```
WARNING:root:Defaulting to wildcard shard mask as none supplied
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-f9caa2b3fd1d> in <module>
----> 1 api.sync(api.contracts.create(owner, contract, 10000))

~/anaconda3/envs/python36/lib/python3.6/site-packages/fetchai_ledger_api-0.9.2-py3.6.egg/fetchai/ledger/api/__init__.py in sync(self, txs, timeout)
     89                 failures = ['{}:{}'.format(tx_status.digest_hex, tx_status.status) \
     90                             for tx_status in failed_this_round]
---> 91                 raise RuntimeError('Some transactions have failed: {}'.format(', '.join(failures)))
     92 
     93             successful_this_round = [status for status in remaining_statuses if status.successful]

RuntimeError: Some transactions have failed: fff70c2dd4bf7f5a880ff941ad6e009c9c16d0fa06dd107eb2af6d613474532c:Chain Code Execution Failure
```

Three questions here:
1) Can @init constructor function be blank or do you always have to pass an address there, even if u don't use it? i.e. `constructor(owner: Address)`
2) Do I need to use the most updated Python API now as I'm still using 0.9.x? Even if I use the latest Python API, would it still be compatible with ledger v0.9.x?
3) Maybe it is not possible to do a persistent Array and need to do a sharded Address with key of Int32?

**Comment by NelisDrost** [comment]
1 - You should always use the `constructor(owner: Address)` pattern for the constructor, even if you don't use the data
2 - The latest SDK (0.10.0-alpha6) should be compatible with the latest ledger version, which you should also be using
3 - What you're doing should be possible, note that I think you need to instantiate the  array to the correct length `Array<Address>(16)`. Using sharded globals should also be possible, but note that the key will always be a string or Address, you'll need to cast your ints with .ToString() - in this particular example I think the approach you're already taking fits better.

**Comment by Kevin-Chen0** [comment]
Thanks for the tips, I have updated to **0.10.0-alpha6** for SDK and **v0.10.0-alpha25** for Ledger. You can see the current contract [here](https://github.com/fetchai/etch-demos/blob/master/demos/pet-shop/adoption.etch). However, I'm still getting the `Some transactions have failed` error, as you can see in the [guide](https://github.com/fetchai/etch-demos/blob/master/demos/guide.ipynb) `In [27]`.

If I tried to change to Array<Address>(16) in `persistent adopters : Array<Address>;` or `function getAdopters() : Array<Address>`, it won't even let me compile, so I don't think that is the solution.

**Comment by Kevin-Chen0** [comment]
This is resolved, thank you @NelisDrost.
