### ISSUE TITLE
Failed to trigger adopt() from pet-shop contract in test.py

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/etch-demos#2]
In test.py, I run the following:

`result = api.sync(contract.action(api, 'adopt', fet_tx_fee, [entity1], pet_id))`

But got the following error:

`AttributeError: 'Tree' object has no attribute 'value'`

**Comment by Kevin-Chen0** [comment]
See interact-checkpoint.ipynb for reference:

https://github.com/fetchai/etch-demos/blob/master/demos/.ipynb_checkpoints/interact-checkpoint.ipynb

**Comment by wkaluza** [comment]
Looks like a Python Etch parser hiccup.

**Comment by NelisDrost** [comment]
This was caused by an issue parsing globals with template types, fixed in https://github.com/fetchai/ledger-api-py/pull/66

**Comment by NelisDrost** [comment]
The PR above has been merged, and a new version of the api released on PyPi as 0.10.0-alpha6, this issue should now be resolved.

**Comment by Kevin-Chen0** [comment]
After using the latest version, this has been resolved. Thank you @NelisDrost.
